name: auto build sphinx document

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: git setting
        run: |
          git config --local user.email "githubaction@action.action"
          git config --local user.name "githubaction"

      - name: Create a new branch or reset an existing branch
        run: |
          git checkout -b doc || git checkout doc && git reset --hard main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"

      - name: Install Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2

      - name: Install Packages
        run: |
            poetry install
      
      - name: Build Documents
        run: |
            rm doc/source/apidoc/* -rf 
            poetry run sphinx-apidoc -f -e -o doc/source/apidoc src/dbcquantum --module-first
            (cd doc && poetry run make html)
            mv doc/build/html/ docs

      - name: Commit compiled files
        run: |
          short_commit_sha=$(git log -1 --pretty='%h')
          git add -A
          git commit -m "Auto compiled from $short_commit_sha" || echo "No changes to commit"
          git push origin doc --force